services:
  rasa:
    image: rasa/rasa:3.6.20-full
    container_name: rasa-service
    command:
      [
        "run",
        "--enable-api",
        "--cors",
        "http://localhost:3000",
        "--debug"
      ]
    volumes:
      - ./rasa:/app
    user: "1000"
    networks:
      app-network:
    ports:
      - 5005:5005

  frontend:
    image: node:18-slim
    container_name: frontend
    command:
      [
        "npm",
        "run",
        "start"
      ]
    volumes:
      - ./:/app
    networks:
      app-network:
    working_dir: /app
    depends_on:
      - rasa
    ports:
      - 3000:3000

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/29